### ISSUE TITLE
Beschreibung für Lasercutter

### ISSUE THREAD

**Issue by MorMundHS-MA** [MorMundHS-MA/innospace-wiki#1]
## Must have:
- [x] Anleitung wie man zu dem Lasercutter connected
- [ ] Anleitung Drucken mit Illustrator
- [ ] Materialien und Einstellung (Verweis auf Aushänge an der Wand?)

## Nice to have:
- [ ] Anleitung Drucken mit PDF
